name: The New Yorker Magazine
run-name: 'The New Yorker Magazine: ${{ github.ref_name }}'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  worker:
    runs-on: ubuntu-latest
    env:
      output: converted_ebooks
      publisher: plsy1.github.io
      author: y1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        if: ${{ success() }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Calibre
        if: ${{ success() }}
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 libopengl0 libxcb-cursor0
          url=https://download.calibre-ebook.com/linux-installer.sh
          sudo -v && wget -nv -O- $url | sudo sh /dev/stdin
      - name: Converting Ebook
        if: ${{ success() }}
        run: |
          mkdir -p $output
          convert_ebook() {
            recipe_name="The New Yorker Magazine"
            recipe_path="${recipe_name}.recipe"
            echo "Converting \"$recipe_path\"..."
            ebook_name="${recipe_path%.*}"
            
            # EPUB
            epub_path="$ebook_name.epub"
            echo "Converting \"$recipe_path\" > \"$epub_path\"..."
            arguments="--authors=\"$author\" --publisher=\"$publisher\""
            cover="covers/${ebook_name}.png"
            if [ -f "$cover" ]; then arguments+=" --cover=\"$cover\""; fi
            style="styles/${ebook_name}.css"
            if [ -f "$style" ]; then arguments+=" --extra-css=\"$style\""; fi
            echo $arguments | xargs ebook-convert "$recipe_path" "$epub_path"
            title=$(ebook-meta "$epub_path" | grep '^Title *:' | sed 's/^Title *: *\(.*\)/\1/')
            new_epub_path="${output}/${title}.epub"
            echo "Renaming \"$epub_path\" > \"$new_epub_path\""
            mv "$epub_path" "$new_epub_path"
        
            # EPUB -> PDF
            epub_file="${output}/${title}.epub"
            pdf_path="${output}/${title}.pdf"
            echo "Converting \"$epub_file\" to PDF > \"$pdf_path\"..."
            pdf_arguments="--authors=\"$author\" --publisher=\"$publisher\""
            if [ -f "$cover" ]; then pdf_arguments+=" --cover=\"$cover\""; fi
            if [ -f "$style" ]; then pdf_arguments+=" --extra-css=\"$style\""; fi
            echo $pdf_arguments | xargs ebook-convert "$epub_file" "$pdf_path"

            # Extract cover image
            cover_image="/cover/cover.jpg"
            ebook-meta "$epub_path" --get-cover="$cover_image"
            echo "Cover extracted and saved to $cover_image"
          }
          
          convert_ebook

      - name: Format Files
        if: ${{ success() }}
        run: |
          python helper/ny.py

      - name: Push to 'magzines' branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin magzines
          git checkout magzines
          mkdir -p the_new_yorker

          if [ -d "the_new_yorker/${{ env.DATE }}" ]; then
            echo "Directory the_new_yorker/${{ env.DATE }} already exists, stop."
            exit 0
          else
            mv $output/${{ env.DATE }} the_new_yorker/
            echo "Moved $output/${{ env.DATE }} to the_new_yorker/"
          fi
          git add the_new_yorker/*
          if [[ $(git diff --cached --quiet || echo "changes") == "changes" ]]; then
            git commit -m "Update The New Yorker Magazine"
            git push origin magzines
          else
            echo "No changes to push."
          fi
        
