name: The New Yorker Magazine
run-name: 'The New Yorker Magazine: ${{ github.ref_name }}'

on:
  workflow_dispatch:
    inputs:
      issue_date:
        description: 'Issue Date (YYYY-MM-DD)'
        required: false
  schedule:
    - cron: '0 1 * * *'

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch and Process
        uses: ./.github/actions/fetch-mag
        with:
          mag_id: ny
          mag_name: "The New Yorker Magazine"
          issue_date: ${{ github.event.inputs.issue_date }}

