name: The Economist
run-name: "The Economist: ${{ github.ref_name }}"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 5"
    - cron: "0 4 * * 6"
    - cron: "0 4 * * 0"

jobs:
  worker:
    runs-on: ubuntu-latest
    env:
      output: converted_ebooks
      publisher: plsy1.github.io
      author: y1

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 3: Install Calibre
      - name: Install Calibre
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 libopengl0 libxcb-cursor0
          url=https://download.calibre-ebook.com/linux-installer.sh
          sudo -v && wget -nv -O- $url | sudo sh /dev/stdin

      # Step 4: Convert Ebook
      - name: Converting Ebook
        run: |
          mkdir -p $output
          convert_ebook() {
            recipe_name="The Economist"
            recipe_path="${recipe_name}.recipe"
            echo "Converting \"$recipe_path\"..."
            ebook_name="${recipe_path%.*}"

            # Convert to EPUB
            epub_path="$ebook_name.epub"
            echo "Converting \"$recipe_path\" > \"$epub_path\"..."
            ebook-convert "$recipe_path" "$epub_path"

            # Extract cover image
            cover_image="${output}/cover.jpg"
            ebook-meta "$epub_path" --get-cover="$cover_image"
            echo "Cover extracted and saved to $cover_image"

            # Rename EPUB
            title=$(ebook-meta "$epub_path" | grep '^Title *:' | sed 's/^Title *: *\(.*\)/\1/')
            new_epub_path="${output}/${title}.epub"
            mv "$epub_path" "$new_epub_path"

            # Convert to PDF
            epub_file="${output}/${title}.epub"
            pdf_path="${output}/${title}.pdf"
            echo "Converting \"$epub_file\" to PDF > \"$pdf_path\"..."
            ebook-convert "$epub_file" "$pdf_path"
          }

          convert_ebook

      - name: Format Files
        if: ${{ success() }}
        run: |
          python helper/te.py

      - name: Push to 'magzines' branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin magzines
          git checkout magzines
          mkdir -p the_economist

          if [ -d "the_economist/$DATE" ]; then
            echo "Directory the_economist/$DATE already exists, stop."
            exit 0
            
          else
            mv $output/the_economist/$DATE the_economist/
            echo "Moved $output/the_economist/$DATE to the_economist/"
          fi
          git add the_economist/*
          if [[ $(git diff --cached --quiet || echo "changes") == "changes" ]]; then
            git commit -m "Update The Economist"
            git push origin magzines
          else
            echo "No changes to push."
          fi
