name: The Economist
run-name: "The Economist: ${{ github.ref_name }}"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 5"
    - cron: "0 4 * * 6"
    - cron: "0 4 * * 0"

jobs:
  worker:
    runs-on: ubuntu-latest
    env:
      output: converted_ebooks
      publisher: plsy1.github.io
      author: y1

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 3: Install Calibre
      - name: Install Calibre
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 libopengl0 libxcb-cursor0
          url=https://download.calibre-ebook.com/linux-installer.sh
          sudo -v && wget -nv -O- $url | sudo sh /dev/stdin

      # Step 4: Convert Ebook
      - name: Converting Ebook
        run: |
          mkdir -p $output
          convert_ebook() {
            recipe_name="The Economist"
            recipe_path="${recipe_name}.recipe"
            echo "Converting \"$recipe_path\"..."
            ebook_name="${recipe_path%.*}"

            # Convert to EPUB
            epub_path="$ebook_name.epub"
            echo "Converting \"$recipe_path\" > \"$epub_path\"..."
            ebook-convert "$recipe_path" "$epub_path"

            # Extract cover image
            cover_image="${output}/cover.jpg"
            ebook-meta "$epub_path" --get-cover="$cover_image"
            echo "Cover extracted and saved to $cover_image"

            # Rename EPUB
            title=$(ebook-meta "$epub_path" | grep '^Title *:' | sed 's/^Title *: *\(.*\)/\1/')
            new_epub_path="${output}/${title}.epub"
            mv "$epub_path" "$new_epub_path"

            # Convert to PDF
            epub_file="${output}/${title}.epub"
            pdf_path="${output}/${title}.pdf"
            echo "Converting \"$epub_file\" to PDF > \"$pdf_path\"..."
            ebook-convert "$epub_file" "$pdf_path"
          }

          convert_ebook

      # Step 5: Rename files with formatted date and create subdirectory
      - name: Rename Files and Create Subdirectory
        run: |
          for file in "$output"/*.{epub,pdf}; do
            if [ -f "$file" ]; then
              if [[ "$file" =~ \[([A-Za-z]+)\ ([0-9]{1,2}),\ ([0-9]{4})\] ]]; then
                month="${BASH_REMATCH[1]}"
                day="${BASH_REMATCH[2]}"
                year="${BASH_REMATCH[3]}"
                case $month in
                  Jan) month_num="01" ;;
                  Feb) month_num="02" ;;
                  Mar) month_num="03" ;;
                  Apr) month_num="04" ;;
                  May) month_num="05" ;;
                  Jun) month_num="06" ;;
                  Jul) month_num="07" ;;
                  Aug) month_num="08" ;;
                  Sep) month_num="09" ;;
                  Oct) month_num="10" ;;
                  Nov) month_num="11" ;;
                  Dec) month_num="12" ;;
                  *) month_num="01" ;;
                esac

                formatted_date="${year}${month_num}$(printf "%02d" $day)"
                echo "DATE=$formatted_date" >> $GITHUB_ENV
                base_name=$(basename "$file" .${file##*.})
                new_name="${formatted_date} - The Economist.${file##*.}"
                
                # Create the subdirectory based on the formatted date
                mkdir -p "$output/the_economist/$formatted_date"

                # Move files (EPUB, PDF, and cover image) to the subdirectory
                mv "$file" "$output/the_economist/$formatted_date/$new_name"
                echo "Renamed and moved $file to $output/the_economist/$formatted_date/$new_name"

                # Move cover image to the subdirectory
                cover_image="${output}/cover.jpg"
                if [ -f "$cover_image" ]; then
                  mv "$cover_image" "$output/the_economist/$formatted_date/cover.jpg"
                  echo "Moved cover image $cover_image to $output/the_economist/$formatted_date/cover.jpg"
                fi
              else
                echo "Skipping file: $file (no valid date found)"
              fi
            fi
          done

      # Step 6: Push to 'magzines' branch
      - name: Push to 'magzines' branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin magzines
          git checkout magzines
          mkdir -p the_economist
          # Check if directory exists before moving files
          if [ -d "the_economist/$DATE" ]; then
            echo "Directory the_economist/$DATE already exists, skipping move."
          else
            mv $output/the_economist/$DATE the_economist/
            echo "Moved $output/the_economist/$DATE to the_economist/"
          fi
          mv $output/the_economist/$DATE the_economist/
          git add the_economist/*
          if [[ $(git diff --cached --quiet || echo "changes") == "changes" ]]; then
            git commit -m "Update The Economist"
            git push origin magzines
          else
            echo "No changes to push."
          fi
