name: The Economist
run-name: "The Economist: ${{ github.ref_name }}"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
jobs:
  worker:
    runs-on: ubuntu-latest
    env:
      output: converted_ebooks
      publisher: plsy1.github.io
      author: y1

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 3: Install Calibre
      - name: Install Calibre
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 libopengl0 libxcb-cursor0
          url=https://download.calibre-ebook.com/linux-installer.sh
          sudo -v && wget -nv -O- $url | sudo sh /dev/stdin

      # Step 4: Convert Ebook
      - name: Converting Ebook
        run: |
          mkdir -p $output
          convert_ebook() {
            recipe_name="The Economist"
            recipe_path="${recipe_name}.recipe"
            echo "Converting \"$recipe_path\"..."
            ebook_name="${recipe_path%.*}"

            # Convert to EPUB
            epub_path="$ebook_name.epub"
            echo "Converting \"$recipe_path\" > \"$epub_path\"..."
            convert_output=$(ebook-convert "$recipe_path" "$epub_path" 2>&1 | tee convert.log)

            # Extract cover image
            cover_image="${output}/cover.jpg"
            ebook-meta "$epub_path" --get-cover="$cover_image"
            echo "Cover extracted and saved to $cover_image"

            # Rename EPUB
            #title=$(ebook-meta "$epub_path" | grep '^Title *:' | sed 's/^Title *: *\(.*\)/\1/')
            title=$(echo "$convert_output" | grep -oP 'images/\K\d{8}' | head -n 1)
            echo "DATE=$title" >> $GITHUB_ENV

            book_name="$title - The Economist"
            
            new_epub_path="${output}/${book_name}.epub"
            mv "$epub_path" "$new_epub_path"

            # Convert to PDF
            epub_file="${output}/${book_name}.epub"
            pdf_path="${output}/${book_name}.pdf"
            echo "Converting \"$epub_file\" to PDF > \"$pdf_path\"..."
            ebook-convert "$epub_file" "$pdf_path"
          }

          convert_ebook

      - name: Upload output directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DATE }}
          path: |
            converted_ebooks
            convert.log
      - name: Push to 'magzines' branch
        run: |
          git config user.name "plsy1"
          git config user.email "plsy1@users.noreply.github.com"

          git fetch origin magzines
          git checkout magzines
          mkdir -p the_economist
          
          if [ -d "the_economist/$DATE" ]; then
            echo "Directory the_economist/$DATE already exists, stop."
            exit 0
          else
            mv $output the_economist/$DATE
            echo "Moved $output to the_economist/$DATE"
          fi
          
          git add the_economist/*
          if [[ $(git diff --cached --quiet || echo "changes") == "changes" ]]; then
            git commit -m "Update The Economist"
            git push origin magzines
          else
            echo "No changes to push."
          fi
        

