name: The Economist
run-name: "The Economist: ${{ github.ref_name }}"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch and Process
        uses: ./.github/actions/fetch-mag
        with:
          mag_id: te
          mag_name: "The Economist"

