name: TIME Magazine
run-name: 'TIME Magazine: ${{ github.ref_name }}'

on:
  workflow_dispatch:
    inputs:
      issue_url:
        description: 'Issue URL (Optional, for old issues)'
        required: false
  schedule:
    - cron: '0 0 * * *'

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch and Process
        uses: ./.github/actions/fetch-mag
        with:
          mag_id: tm
          mag_name: "TIME Magazine"
          issue_date: ${{ github.event.inputs.issue_url }}

